# Q1

In [5]:
import numpy as np
A=np.array([[0,1,1,0],[0,0,1,0],[0,0,0,1],[1,1,0,0]])
X=[]
eigen=[0]
X.append(np.array([[1],[1],[1],[1]]))
print(A,'\n\n',X)
print("-----------------------------------------")

i=0
while len(eigen)==1 or eigen[i]!=eigen[i-1]:
    X.append(np.matmul(A,X[i]))
    eigen.append(max(X[i+1]))
    X[i+1]= np.round(X[i+1]/eigen[i+1],4)
    print("Iteration",i+1,":")
    print(X[i+1],"\t",eigen[i+1])
    print()
    i+=1

[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 1 0 0]] 

 [array([[1],
       [1],
       [1],
       [1]])]
-----------------------------------------
Iteration 1 :
[[1. ]
 [0.5]
 [0.5]
 [1. ]] 	 [2]

Iteration 2 :
[[0.6667]
 [0.3333]
 [0.6667]
 [1.    ]] 	 [1.5]

Iteration 3 :
[[1.    ]
 [0.6667]
 [1.    ]
 [1.    ]] 	 [1.]

Iteration 4 :
[[1. ]
 [0.6]
 [0.6]
 [1. ]] 	 [1.6667]

Iteration 5 :
[[0.75 ]
 [0.375]
 [0.625]
 [1.   ]] 	 [1.6]

Iteration 6 :
[[0.8889]
 [0.5556]
 [0.8889]
 [1.    ]] 	 [1.125]

Iteration 7 :
[[1.    ]
 [0.6154]
 [0.6923]
 [1.    ]] 	 [1.4445]

Iteration 8 :
[[0.8095]
 [0.4286]
 [0.619 ]
 [1.    ]] 	 [1.6154]

Iteration 9 :
[[0.8461]
 [0.5   ]
 [0.8077]
 [1.    ]] 	 [1.2381]

Iteration 10 :
[[0.9715]
 [0.6   ]
 [0.7429]
 [1.    ]] 	 [1.3461]

Iteration 11 :
[[0.8545]
 [0.4727]
 [0.6363]
 [1.    ]] 	 [1.5715]

Iteration 12 :
[[0.8356]
 [0.4794]
 [0.7535]
 [1.    ]] 	 [1.3272]

Iteration 13 :
[[0.9376]
 [0.573 ]
 [0.7605]
 [1.    ]] 	 [1.315]

Iteration 14 :
[[0.8828]
 [0.

In [7]:
# For calculating eigen values i.e roots of the characteristic eq.
import numpy as np
np.linalg.eigvals(A)

array([ 1.39533699+0.j        , -0.46035519+1.13931768j,
       -0.46035519-1.13931768j, -0.47462662+0.j        ])

# Q2

In [2]:
import pandas as pd
import numpy as np

en_show = pd.read_csv("ASN_1.csv")

df = pd.DataFrame(en_show)
df.index=range(1,11)
df

Shows  SCAM1992  THE FAMILY MAN  SPECIAL OPS  PAATAL LOK  \
1        SCAM 1992         1               2            2           2   
2   THE FAMILY MAN         0               1            2           2   
3      SPECIAL OPS         0               0            1           2   
4       PAATAL LOK         0               0            0           1   
5        PANCHAYAT         0               2            2           2   
6     SACRED GAMES         0               2            2           2   
7         MIRZAPUR         0               0            0           2   
8         PITCHERS         0               2            2           2   
9             ASUR         0               0            0           2   
10    KOTA FACTORY         0               2            2           2   

    PANCHAYAT  SACRED GAMES  MIRZAPUR  PITCHERS  ASUR  KOTA FACTORY  
1           2             2         2         2     2             2  
2           0             0         2         0     2             0  
3           0             0         2         0     2             0  
4           0             0         0         0     0             0  
5           1             1         2         0     2             0  
6           1             1         2         0     2             0  
7           0             0         1         0     1             0  
8           2             2         2         1     2             2  
9           0             0         1         0     1             0  
10          2             2         2         0     2             1

In [3]:
A=df.iloc[:,1:].to_numpy()
print("Matrix:")
print(A)

Matrix:
[[1 2 2 2 2 2 2 2 2 2]
 [0 1 2 2 0 0 2 0 2 0]
 [0 0 1 2 0 0 2 0 2 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 2 2 2 1 1 2 0 2 0]
 [0 2 2 2 1 1 2 0 2 0]
 [0 0 0 2 0 0 1 0 1 0]
 [0 2 2 2 2 2 2 1 2 2]
 [0 0 0 2 0 0 1 0 1 0]
 [0 2 2 2 2 2 2 0 2 1]]


In [4]:
import numpy as np
X=[]
eigen=[0]
X.append(np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]]))
print(A,'\n\n',X)
print("-----------------------------------------")

i=0
while len(eigen)==1 or np.round(eigen[i],4)!=np.round(eigen[i-1],4):
    X.append(np.matmul(A,X[i]))
    eigen.append(max(X[i+1]))
    X[i+1]= np.round(X[i+1]/eigen[i+1],4)
    print("Iteration",i+1,":")
    print(X[i+1],"\t",eigen[i+1])
    print()
    i+=1

[[1 2 2 2 2 2 2 2 2 2]
 [0 1 2 2 0 0 2 0 2 0]
 [0 0 1 2 0 0 2 0 2 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 2 2 2 1 1 2 0 2 0]
 [0 2 2 2 1 1 2 0 2 0]
 [0 0 0 2 0 0 1 0 1 0]
 [0 2 2 2 2 2 2 1 2 2]
 [0 0 0 2 0 0 1 0 1 0]
 [0 2 2 2 2 2 2 0 2 1]] 

 [array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])]
-----------------------------------------
Iteration 1 :
[[1.    ]
 [0.4737]
 [0.3684]
 [0.0526]
 [0.6316]
 [0.6316]
 [0.2105]
 [0.8947]
 [0.2105]
 [0.7895]] 	 [19]

Iteration 2 :
[[1.    ]
 [0.2265]
 [0.1381]
 [0.0055]
 [0.4088]
 [0.4088]
 [0.0552]
 [0.8011]
 [0.0552]
 [0.6243]] 	 [9.5262]

Iteration 3 :
[[1.000e+00]
 [1.139e-01]
 [5.740e-02]
 [9.000e-04]
 [2.759e-01]
 [2.759e-01]
 [1.880e-02]
 [7.206e-01]
 [1.880e-02]
 [4.995e-01]] 	 [6.447]

Iteration 4 :
[[1.000e+00]
 [6.160e-02]
 [2.710e-02]
 [2.000e-04]
 [1.957e-01]
 [1.957e-01]
 [7.900e-03]
 [6.533e-01]
 [7.900e-03]
 [4.075e-01]] 	 [4.9634]

Iteration 5 :
[[1.    ]
 [0.0359]
 [0.